version: '3.7'

services:
  web_service:
    build: ./web-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./web-service/:/app/
    ports:
      - 8001:8000
    environment:
      #- BASE_URL=
      #- API_KEY=
      #- ORG_ID=
      #- ISOLATION_SENSITIVITY=
